# -*- coding: utf-8 -*-
"""day51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ikhmj9h8Al14neAzTk0WtVKfEXSrsU9c
"""

from sklearn.datasets import make_regression
import numpy as np

X,y = make_regression(n_samples = 4,n_features=1,n_informative=1,n_targets=1,noise=80,random_state=13)

import matplotlib.pyplot as plt
plt.scatter(X,y)

# Lets apply the OLS
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X,y)

reg.coef_

reg.intercept_

plt.scatter(X,y)
plt.plot(X,reg.predict(X),color='red')

# Lets apply Gradient Descent assuming slope is constant m = 78.35
# and let's assume the starting value for intercept b = 0

y_pred = ((78.35*X ) +100).reshape(4)

import matplotlib.pyplot as plt
plt.scatter(X,y)
plt.plot(X,reg.predict(X),color='red',label='OLS')
plt.plot(X,y_pred,color='#00a65a',label='b = 0')
plt.legend()
plt.show()

m = 78.35
b = 100

loss_slope = -2 * np.sum(y-m*X.ravel() - b)
loss_slope

# lets take the lerning rate = 0.1\

lr = 0.1


step_size = loss_slope * lr
step_size

# Calculating the new intercept

b = b - step_size
b

m = 78.35
b_initial = 100
y_pred_initial = ((m*X) + b_initial).reshape(4)

# The current value of 'b' in the kernel is the updated one
y_pred_updated = ((m*X) + b).reshape(4)

plt.scatter(X,y)
plt.plot(X,reg.predict(X),color='red',label='OLS')
plt.plot(X,y_pred_initial,color='#00a65a',label='b = {}'.format(b_initial))
plt.plot(X,y_pred_updated,color='#A3E4D7',label='b = {}'.format(b))
plt.legend()
plt.show()

# Iteration 2
loss_slope = -2 * np.sum(y-m*X.ravel() - b)
loss_slope

step_size = loss_slope*lr
step_size

b = b-step_size
b

m = 78.35
b_initial = 100 # Initial b value

# b value after 1st iteration, from output of cell eTErN3jAHeQC
b_iter1 = 40.927763408209216

# The current 'b' in the kernel is the value after the 2nd iteration
# Calculate y_pred for the current 'b'
y_pred_iter2 = ((m * X) + b).reshape(4)

plt.scatter(X,y)
plt.plot(X,reg.predict(X),color='red',label='OLS')
plt.plot(X,y_pred_initial,color='#00a65a',label=f'b = {b_initial} (iter 0)')
plt.plot(X,y_pred_updated,color='#A3E4D7',label=f'b = {b_iter1:.2f} (iter 1)')
plt.plot(X,y_pred_iter2,color='purple',label=f'b = {b:.2f} (iter 2)')
plt.legend()
plt.show()

# iteration 3
loss_slope = -2 * np.sum(y-m*X.ravel()-b)
loss_slope

step_size = loss_slope*lr
step_size

b = b - step_size
b

m = 78.35
b_initial = 100 # Initial b value

# b value after 1st iteration (from cell eTErN3jAHeQC output)
b_iter1 = 40.927763408209216

# b value after 2nd iteration (from cell 6gOMjj5fJtFz output)
b_iter2 = 29.11331608985106

# The current 'b' in the kernel is the value after the 3rd iteration
b_iter3 = b

# Calculate y_pred for each iteration using the correct 'b' value
# y_pred_initial, y_pred_updated, y_pred_iter2 are already in kernel from previous cells.

# Calculate y_pred for the current 'b' (after 3rd iteration)
y_pred_iter3 = ((m * X) + b_iter3).reshape(4) # Corrected -b to +b

plt.figure(figsize=(15,15))
plt.scatter(X,y)
plt.plot(X,reg.predict(X),color='red',label='OLS')
plt.plot(X,y_pred_initial,color='#00a65a',label=f'b = {b_initial} (iter 0)')
plt.plot(X,y_pred_updated,color='#A3E4D7',label=f'b = {b_iter1:.2f} (iter 1)')
plt.plot(X,y_pred_iter2,color='orange',label=f'b = {b_iter2:.2f} (iter 2)')
plt.plot(X,y_pred_iter3,color='purple',label=f'b = {b_iter3:.2f} (iter 3)')
plt.legend()
plt.show()

b = -100
m = 78.35
b = 0.01

epochs = 100

for i in range(epochs):
  loss_slope = -2 * np.sum(y - m*X.ravel()-b)
  b = b - (lr*loss_slope)
  y_pred = m * X + b

  plt.plot(X,y_pred)

plt.scatter(X,y)

